matrix:
  include:
  - language: bash
    script:
    - bash linux_downloader.sh
  - language: bash
    services:
      - docker
    script:
      - docker pull microsoft/powershell
      - docker run -v $(pwd)/windows:/data microsoft/powershell /bin/sh -c "cd /data; chmod +x *.ps1; pwsh ./windows-downloader.ps1"

